helm-extra-args: --timeout 300s
check-version-increment: true
debug: true
namespace: microgateway-validation
release-label: release
chart-repos: 
        - bitnami=https://charts.bitnami.com/bitnami
        - https://ealenn.github.io/charts
        - https://libuweber.github.io/microgateway
