protocol: TCP
exposedport: 8080
port: 8080
imagePullSecrets: []
image:
    repository: julianbe/microgateway
    tag: testservlet-1.13
    pullPolicy: IfNotPresent

readinessProbe:
    path: /TestServlet/
    scheme: HTTP
    initialDelaySeconds: 5
    failureThreshold: 3
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 4

livenessProbe:
    path: /TestServlet/
    scheme: HTTP
    initialDelaySeconds: 10
    failureThreshold: 3
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 4